#!/usr/bin/env python3
"""Generate src/frontend/frontend_bundle.h from src/frontend/{index.html,style.css,app.js}.

Inlines style.css and app.js into index.html, gzip-compresses the result, and
embeds it as a uint8_t array so HttpServerModule can serve it with
Content-Encoding: gzip without touching the filesystem.

Run after editing any frontend source — the committed bundle must match a
fresh regeneration, enforced by scripts/check_bundle.py in CI and pre-commit.

Usage:
    uv run scripts/gen_frontend_bundle.py
"""
import gzip
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FRONTEND = ROOT / "src" / "frontend"
SRC_HTML = FRONTEND / "index.html"
SRC_CSS = FRONTEND / "style.css"
SRC_JS = FRONTEND / "app.js"
OUT_HEADER = FRONTEND / "frontend_bundle.h"

BYTES_PER_LINE = 16


def to_c_array(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i:i + BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def build_bundle():
    """Inline CSS+JS into HTML, gzip-compress, return (raw, gz) bytes.
    mtime=0 keeps the gzip header deterministic so the drift check sees
    identical bytes for identical sources."""
    for path in (SRC_HTML, SRC_CSS, SRC_JS):
        if not path.exists():
            print(f"ERROR: source not found: {path}", file=sys.stderr)
            sys.exit(1)
    html = SRC_HTML.read_text(encoding="utf-8")
    css = SRC_CSS.read_text(encoding="utf-8").rstrip("\n")
    js = SRC_JS.read_text(encoding="utf-8").rstrip("\n")
    html = html.replace('<link rel="stylesheet" href="style.css">', f'<style>\n{css}\n</style>')
    html = html.replace('<script src="app.js"></script>', f'<script>\n{js}\n</script>')
    raw = html.encode("utf-8")
    gz = gzip.compress(raw, compresslevel=9, mtime=0)
    return raw, gz


def render_header(raw_len: int, gz: bytes) -> str:
    ratio = len(gz) / raw_len * 100
    return (
        f"#pragma once\n"
        f"// Auto-generated by scripts/gen_frontend_bundle.py -- do not edit.\n"
        f"// Regenerate: uv run scripts/gen_frontend_bundle.py\n"
        f"// Sources:    src/frontend/index.html + style.css + app.js\n"
        f"// Original:   {raw_len} bytes  Compressed: {len(gz)} bytes  ({ratio:.0f}%)\n"
        f"// clang-format off\n"
        f"\n"
        f"static const uint8_t FRONTEND_HTML_GZ[] = {{\n"
        f"{to_c_array(gz)}\n"
        f"}};\n"
        f"static const size_t FRONTEND_HTML_GZ_LEN = sizeof(FRONTEND_HTML_GZ);\n"
    )


def main():
    raw, gz = build_bundle()
    header = render_header(len(raw), gz)
    OUT_HEADER.write_text(header, encoding="utf-8")
    rel = OUT_HEADER.relative_to(ROOT)
    ratio = len(gz) / len(raw) * 100
    print(f"[gen_frontend_bundle] wrote {rel} ({len(raw)} -> {len(gz)} bytes, {ratio:.0f}%)")


if __name__ == "__main__":
    main()
